---
swagger: "2.0"
info:
  description: "API desenvolvida para Computação em Nuvem 2022"
  version: "1.0.0"
  title: "Steam Reviews API"
  contact:
    email: "miguelescsilva@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/ComputacaoNuvem2022/StreamReviews/1.0.0"
tags:
- name: "Steam Service"
  description: "General logic of the system"
- name: "Reviews Service"
  description: "Manage the game reviews of steam"
- name: "Users Service"
  description: "Manage the users that review games on steam"
- name: "Games Service"
  description: "Manage the games of steam"
- name: "Authentication Service"
  description: "Manage the users of system"
schemes:
- "https"
paths:
  /steam/activeusers:
    get:
      tags:
      - "Steam Service"
      summary: "Get most active users"
      description: "Get the top 10 most active users"
      operationId: "get_active_users"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserItem"
        "400":
          description: "invalid input, object invalid"
      x-swagger-router-controller: "controllers.steam_service_controller"
definitions:
  UserItem:
    type: "object"
    required:
    - "id"
    - "lastPlayed"
    - "numGames"
    - "reviewPlayTime"
    - "totalPlayTime"
    - "twoWeeksPlaytime"
    properties:
      id:
        type: "integer"
        example: 76561198949504110
      numGames:
        type: "integer"
        example: 70
      totalPlayTime:
        type: "number"
        example: 300.69999999999998863131622783839702606201171875
      twoWeeksPlaytime:
        type: "number"
        example: 28.699999999999999289457264239899814128875732421875
      reviewPlayTime:
        type: "number"
        example: 30
      lastPlayed:
        type: "string"
        example: "2/07/2020"
    example:
      totalPlayTime: 300.69999999999998863131622783839702606201171875
      twoWeeksPlaytime: 28.699999999999999289457264239899814128875732421875
      id: 76561198949504110
      numGames: 70
      reviewPlayTime: 30
      lastPlayed: "2/07/2020"
  ReviewsItem:
    type: "object"
    required:
    - "game"
    - "helpful"
    - "language"
    - "recommended"
    - "review"
    properties:
      game:
        type: "string"
        example: "FIFA 22"
      language:
        type: "string"
        example: "English"
      review:
        type: "string"
        example: "It's 2021. This is the first time I have played this. All of the\
          \ good."
      recommended:
        type: "boolean"
        example: true
      helpful:
        type: "boolean"
        example: true
    example:
      game: "FIFA 22"
      review: "It's 2021. This is the first time I have played this. All of the good."
      language: "English"
      helpful: true
      recommended: true
  GamesItem:
    type: "object"
    required:
    - "game"
    - "mostCommonLanguage"
    - "numberOfReviews"
    - "recommendedPercentage"
    properties:
      game:
        type: "string"
        example: "Fifa 22"
      numberOfReviews:
        type: "integer"
        example: 1
      mostCommonLanguage:
        type: "string"
        example: "english"
      recommendedPercentage:
        type: "string"
        example: "100%"
    example:
      game: "Fifa 22"
      mostCommonLanguage: "english"
      numberOfReviews: 1
      recommendedPercentage: "100%"
  UserAuthItem:
    type: "object"
    required:
    - "password"
    - "username"
    properties:
      username:
        type: "string"
        example: "userguest1"
      password:
        type: "string"
        example: "password"
    example:
      password: "password"
      username: "userguest1"
  TokenItem:
    type: "object"
    required:
    - "token"
    properties:
      token:
        type: "string"
        example: "ibsufbaw32432-isufaiefawfg-234234nkawf"
    example:
      token: "ibsufbaw32432-isufaiefawfg-234234nkawf"
